# Generated by Django 5.2.8 on 2025-11-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesapal_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesapalorder',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pesapal_correlation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
